# Generated by Django 2.0.2 on 2018-03-15 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0002_auto_20180315_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earnedachievement',
            old_name='achieve',
            new_name='achievement',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='releaseDate',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dateOfBirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
