# Generated by Django 2.0.2 on 2018-03-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0003_auto_20180315_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, help_text="Enter the user's date of birth", null=True),
        ),
    ]
