# Generated by Django 2.0.2 on 2018-03-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0004_auto_20180315_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Enter the user's date of birth", null=True),
        ),
    ]
