# Generated by Django 2.0.2 on 2018-03-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0005_auto_20180315_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Enter the end time of the event (blank if still ongoing', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Enter the start time of the event', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Enter when the user finished participating in the event (blank if ongoing)', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Enter when the user started participating in the event', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(blank=True, help_text="Enter the user's gender", null=True),
        ),
    ]
