# Generated by Django 2.0.2 on 2018-03-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0006_auto_20180315_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, help_text="Enter the game's release date", null=True),
        ),
    ]
