# Generated by Django 2.0.2 on 2018-03-25 23:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0008_auto_20180316_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('0', 'friends'), ('1', 'pending'), ('2', 'blacklistAB'), ('3', 'blacklistBA'), ('0', 'blacklist')], max_length=1)),
                ('friendA', models.ForeignKey(help_text='Enter the id of the user to whom this friends list belongs', on_delete=django.db.models.deletion.CASCADE, related_name='friendA', to='nintinder.User')),
                ('friendB', models.ForeignKey(help_text='Enter the id of the user who is on the friends list', on_delete=django.db.models.deletion.CASCADE, related_name='friendB', to='nintinder.User')),
            ],
        ),
    ]
