# Generated by Django 2.0.2 on 2018-03-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0009_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
