# Generated by Django 2.0.2 on 2018-03-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0010_remove_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('0', 'friends'), ('1', 'pending'), ('2', 'blacklistAB'), ('3', 'blacklistBA'), ('4', 'blacklist')], max_length=1),
        ),
    ]
