# Generated by Django 2.0.2 on 2018-04-17 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('nintinder', '0011_auto_20180329_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_name', models.CharField(help_text='Enter a username', max_length=64)),
                ('first_name', models.CharField(help_text="Enter the user's first name", max_length=64)),
                ('last_name', models.CharField(help_text="Enter the user's last name", max_length=64)),
                ('location', models.CharField(help_text="Enter the user's location", max_length=256)),
                ('date_of_birth', models.DateField(blank=True, help_text="Enter the user's date of birth", null=True)),
                ('email', models.CharField(help_text="Enter the user's email address", max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='earnedachievement',
            name='user',
            field=models.ForeignKey(help_text='Enter the username of the user who has earned the achievement', on_delete=django.db.models.deletion.CASCADE, to='nintinder.Profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='game',
            field=models.ForeignKey(help_text='Enter the name of the game', on_delete=django.db.models.deletion.CASCADE, to='nintinder.Game'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friendA',
            field=models.ForeignKey(help_text='Enter the id of the user to whom this friends list belongs', on_delete=django.db.models.deletion.CASCADE, related_name='friendA', to='nintinder.Profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friendB',
            field=models.ForeignKey(help_text='Enter the id of the user who is on the friends list', on_delete=django.db.models.deletion.CASCADE, related_name='friendB', to='nintinder.Profile'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(help_text='Enter the username of the user who is interested in a game', on_delete=django.db.models.deletion.CASCADE, to='nintinder.Profile'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(help_text='Enter the id of user participating in the event', on_delete=django.db.models.deletion.CASCADE, to='nintinder.Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
