# Generated by Django 2.0.2 on 2018-04-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0012_auto_20180416_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
