# Generated by Django 2.0.2 on 2018-04-17 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0013_auto_20180416_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnedachievement',
            name='user',
            field=models.ForeignKey(help_text='Enter the username of the user who has earned the achievement', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friendA',
            field=models.ForeignKey(help_text='Enter the id of the user to whom this friends list belongs', on_delete=django.db.models.deletion.CASCADE, related_name='friendA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friendB',
            field=models.ForeignKey(help_text='Enter the id of the user who is on the friends list', on_delete=django.db.models.deletion.CASCADE, related_name='friendB', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(help_text='Enter the username of the user who is interested in a game', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(help_text='Enter the id of user participating in the event', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
