# Generated by Django 2.0.2 on 2018-04-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0014_auto_20180417_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(to='nintinder.Game'),
        ),
    ]
