# Generated by Django 2.0.2 on 2018-04-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0015_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(to='nintinder.Achievement'),
        ),
    ]
