# Generated by Django 2.0.2 on 2018-04-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0016_profile_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earnedachievement',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='earnedachievement',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='nintinder.Achievement'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='nintinder.Game'),
        ),
        migrations.DeleteModel(
            name='EarnedAchievement',
        ),
    ]
