# Generated by Django 2.0.2 on 2018-04-23 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0018_auto_20180422_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buddies',
            field=models.ManyToManyField(blank=True, through='nintinder.Friend', to='nintinder.Profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friendA',
            field=models.ForeignKey(help_text='Enter the id of the user to whom this friends list belongs', on_delete=django.db.models.deletion.CASCADE, related_name='friendA', to='nintinder.Profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friendB',
            field=models.ForeignKey(help_text='Enter the id of the user who is on the friends list', on_delete=django.db.models.deletion.CASCADE, related_name='friendB', to='nintinder.Profile'),
        ),
    ]
