# Generated by Django 2.0.2 on 2018-04-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0019_auto_20180422_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='buddies',
            field=models.ManyToManyField(blank=True, related_name='_profile_buddies_+', through='nintinder.Friend', to='nintinder.Profile'),
        ),
    ]
