# Generated by Django 2.0.2 on 2018-04-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0020_auto_20180423_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('0', 'friends'), ('1', 'pending'), ('2', 'blacklist')], max_length=1),
        ),
    ]
