# Generated by Django 2.0.2 on 2018-04-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0022_auto_20180423_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'friends'), (1, 'pending'), (1, 'blacklist')]),
        ),
    ]
