# Generated by Django 2.0.2 on 2018-04-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0024_auto_20180424_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'friends'), (1, 'pending'), (1, 'blacklist')], null=True),
        ),
    ]
