# Generated by Django 2.0.2 on 2018-04-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nintinder', '0025_auto_20180424_1932'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='interest',
            name='game',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'friends'), (1, 'pending'), (2, 'blacklist')], null=True),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
