from nintinder.models import Game

Game.objects.create(id = 'c464e2b5-eedf-488a-a53c-56fd067c0ee4', name = 'Counter-Strike: Global Offensive', platform = 'PC', publisher = 'Valve Corporation', description = 'The game pits two teams against each other: the Terrorists and the Counter-Terrorists. Both sides are tasked with eliminating the other while also completing separate objectives, the Terrorists, depending on the game mode, must either plant the bomb or defend the hostages, while the Counter-Terrorists must either prevent the bomb from being planted, defuse the bomb, or rescue the hostages. There are eight game modes, all of which have distinct characteristics specific to that mode.', release_date = '2012-08-21')

Game.objects.create(id = '79da553b-3c15-4dc5-a07f-146097304b54', name = 'League of Legends', platform =' PC', publisher = 'Riot Games', description = 'League of Legends (abbreviated LoL) is a multiplayer online battle arena video game developed and published by Riot Games for Microsoft Windows and macOS.', release_date = '2009-10-27');

Game.objects.create(id = 'a3b0a58c-010b-4076-8b00-313e537013ad', name = 'Tom Clancy''s Rainbow Six Siege', platform ='PC', publisher = 'Ubisoft', description = 'Tom Clancys Rainbow Six Siege is a tactical shooter video game developed by Ubisoft Montreal and published by Ubisoft.', release_date = '2015-12-01');
Game.objects.create(id = '94f53507-184d-4d15-849e-814f90864e9a', name = 'Tom Clancy''s Rainbow Six Siege', platform ='Xbox One', publisher = 'Ubisoft', description = 'Tom Clancys Rainbow Six Siege is a tactical shooter video game developed by Ubisoft Montreal and published by Ubisoft.', release_date = '2015-12-01');
Game.objects.create(id = '8c8b100e-4367-4ae3-b6e1-63a892a62e48', name = 'Tom Clancy''s Rainbow Six Siege', platform ='PlayStation 4', publisher = 'Ubisoft', description = 'Tom Clancys Rainbow Six Siege is a tactical shooter video game developed by Ubisoft Montreal and published by Ubisoft.', release_date = '2015-12-01');

Game.objects.create(id = '42880d2a-af71-416f-90ba-fae0ef52f0ff', name = 'Super Smash Bros. Brawl', platform ='Wii', publisher = 'Nintendo', description = 'Super Smash Bros. Brawl[a] is a crossover fighting game, the third installment in the Super Smash Bros. series, developed by Sora Ltd. and Game Arts and published by Nintendo for the Wii video game console.', release_date = '2008-01-31');

Game.objects.create(id = 'c52cfb32-3042-4fc3-9d78-6a93328b8317', name = 'Super Smash Bros. Melee', platform ='GameCube', publisher = 'Nintendo', description = 'Super Smash Bros. Melee is a crossover fighting video game developed by HAL Laboratory and published by Nintendo for the GameCube video game console. ', release_date = '2001-11-21');

Game.objects.create(id = 'acd664fd-1c56-4a8e-b09f-62ae88236325', name = 'Halo 3', platform ='Xbox 360', publisher = 'Microsoft Game Studios', description = 'Halo 3 is a 2007 first-person shooter video game developed by Bungie for the Xbox 360 console. The third installment in the Halo franchise, the game concludes the story arc begun in 2001s Halo: Combat Evolved and continued in 2004s Halo 2.', release_date = '2007-09-25');
Game.objects.create(id = '8285b3a8-847d-485d-8202-7d893c85cb22', name = 'Halo 3', platform ='Xbox One', publisher = 'Microsoft Game Studios', description = 'Halo 3 is a 2007 first-person shooter video game developed by Bungie for the Xbox 360 console. The third installment in the Halo franchise, the game concludes the story arc begun in 2001s Halo: Combat Evolved and continued in 2004s Halo 2.', release_date = '2007-09-25');

Game.objects.create(id = '2d9c199e-e854-441f-ab30-cce96c48f303', name = 'The Elder Scrolls V: Skyrim', platform ='PC', publisher = 'Bethesda Softworks', description = 'The Elder Scrolls V: Skyrim is an open world action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks.', release_date = '2011-11-11');
Game.objects.create(id = '8621e3e9-c60b-40f6-a47d-a68902c70d41', name = 'The Elder Scrolls V: Skyrim', platform ='PlayStation 3', publisher = 'Bethesda Softworks', description = 'The Elder Scrolls V: Skyrim is an open world action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks.', release_date = '2011-11-11');
Game.objects.create(id = '4f2af043-d511-452f-a350-a6ea37571df6', name = 'The Elder Scrolls V: Skyrim', platform ='PlayStation 4', publisher = 'Bethesda Softworks', description = 'The Elder Scrolls V: Skyrim is an open world action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks.', release_date = '2016-10-28');
Game.objects.create(id = '017b8507-5773-4fa2-b13b-103b38b441b9', name = 'The Elder Scrolls V: Skyrim', platform ='Xbox 360', publisher = 'Bethesda Softworks', description = 'The Elder Scrolls V: Skyrim is an open world action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks.', release_date = '2011-11-11');
Game.objects.create(id = '22fae007-2d42-4a93-a3a2-74f48093b117', name = 'The Elder Scrolls V: Skyrim', platform ='Xbox One', publisher = 'Bethesda Softworks', description = 'The Elder Scrolls V: Skyrim is an open world action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks.', release_date = '2016-10-28');
Game.objects.create(id = 'd94e2cbe-ab78-4762-95c8-5a4adfd8cd68', name = 'The Elder Scrolls V: Skyrim', platform ='Nintendo Switch', publisher = 'Bethesda Softworks', description = 'The Elder Scrolls V: Skyrim is an open world action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks.', release_date = '2017-11-17');


Game.objects.create(id = '54fa90b3-729b-4766-ad69-125a40d3cf74', name = 'The Legend of Zelda: Breath of the Wild', platform ='Nintendo Switch', publisher = 'Nintendo', description = 'The Legend of Zelda: Breath of the Wild is an action-adventure game developed and published by Nintendo.', release_date = '2017-03-03');
Game.objects.create(id = 'ecfc687b-c7e9-42a1-a3e1-a92fa45be3a2', name = 'The Legend of Zelda: Breath of the Wild', platform ='Wii U', publisher = 'Nintendo', description = 'The Legend of Zelda: Breath of the Wild is an action-adventure game developed and published by Nintendo.', release_date = '2017-03-03');

